# Generated by Django 5.0.6 on 2025-07-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_matching",
            field=models.BooleanField(default=False),
        ),
    ]
