# Generated by Django 5.0.6 on 2025-08-01 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_is_matching"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_matching",
        ),
    ]
