# Generated by Django 5.0.6 on 2025-08-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemtransaction',
            name='ad_unit_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gemtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('spend', 'Spend'), ('refund', 'Refund'), ('reward', 'Reward')], max_length=20),
        ),
    ]
