# Generated by Django 5.0.6 on 2025-08-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0002_gemtransaction_ad_unit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemtransaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='External transaction ID (e.g., from AdMob)', max_length=255, null=True, unique=True),
        ),
    ]
