# Generated by Django 5.0.6 on 2025-08-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0003_gemtransaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemtransaction',
            name='ad_unit_id',
        ),
        migrations.RemoveField(
            model_name='gemtransaction',
            name='transaction_id',
        ),
    ]
