# Generated by Django 5.0.6 on 2025-08-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchsetting",
            name="radius_km",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
