# Generated by Django 5.0.6 on 2025-08-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0002_matchqueue"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchqueue",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
