# Generated by Django 5.0.6 on 2025-08-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0003_matchqueue_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchrequest",
            old_name="status",
            new_name="matched_user_status",
        ),
        migrations.AddField(
            model_name="matchrequest",
            name="requester_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
