# Generated by Django 5.0.6 on 2025-08-12 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0004_recentmatchexclude"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecentMatchExclude",
        ),
    ]
